# Generated by Django 4.0.2 on 2022-02-28 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_number', models.IntegerField(primary_key=True, serialize=False)),
                ('train_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('train_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.train')),
            ],
        ),
    ]
