# Generated by Django 4.0.2 on 2022-02-28 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        ('shunt_factor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('location', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trip_name', models.CharField(max_length=200)),
                ('train_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.train')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('shunt_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shunt_factor.shunt')),
                ('station_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empolyeeStation.station')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empolyeeStation.trip')),
            ],
        ),
    ]
