# Generated by Django 4.0.2 on 2022-03-09 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number'),
        ('empolyeeStation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('station_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empolyeeStation.station')),
            ],
        ),
    ]
