# Generated by Django 4.0.2 on 2022-03-09 20:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0127023796', max_length=128, region='EG', verbose_name='NATIONAL'),
            preserve_default=False,
        ),
    ]
