# Generated by Django 4.0 on 2021-12-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.PositiveIntegerField(default='30001031100861', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
