# Generated by Django 4.0.2 on 2022-02-28 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shunt',
            fields=[
                ('shunt_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('location', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShuntFactor',
            fields=[
                ('shunt_factor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shunt_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shunt_factor.shunt')),
            ],
        ),
    ]
